# Generated by Django 5.2.6 on 2025-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Yoruba Proverb Text')),
                ('translation', models.TextField(blank=True, null=True, verbose_name='English Translation')),
            ],
            options={
                'verbose_name': 'Proverb',
                'verbose_name_plural': 'Proverbs',
            },
        ),
    ]
