# Generated by Django 4.2.24 on 2025-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverb',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='proverb_audio/', verbose_name='Audio (TTS)'),
        ),
    ]
