# Generated by Django 4.2.24 on 2025-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0004_alter_generalrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverb',
            name='tag',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=10, verbose_name='Proverb Source'),
        ),
    ]
