# Generated by Django 4.2.24 on 2025-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0005_proverb_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverb',
            name='encoded_audio',
            field=models.TextField(blank=True, null=True, verbose_name='Encoded Audio'),
        ),
    ]
